version: "3.7"

services:
    account:
        build: "./atomic/account"
        image: "weihaosmu/account:1.0.0"
        environment:
            - dbURL=mysql+mysqlconnector://is213@host.docker.internal:3306/account
        ports:
            - "5000:5000"

    accessory:
        build: "./atomic/accessory"
        image: "weihaosmu/accessory:1.0.0"
        environment:
            - dbURL=mysql+mysqlconnector://is213@host.docker.internal:3306/accessory
        ports:
            - "5001:5001"

    inventory:
        build: "./atomic/inventory"
        image: "weihaosmu/inventory:1.0.0"
        environment:
            - dbURL=mysql+mysqlconnector://is213@host.docker.internal:3306/inventory
        ports:
            - "5002:5002"

    shop:
        build: "./atomic/shop"
        image: "weihaosmu/shop:1.0.0"
        environment:
            - dbURL=mysql+mysqlconnector://is213@host.docker.internal:3306/shop
        ports:
            - "5003:5003"

    stock:
        build: "./atomic/stock"
        image: "weihaosmu/stock:1.0.0"
        environment:
            - dbURL=mysql+mysqlconnector://is213@host.docker.internal:3306/stock
        ports:
            - "5010:5010"

    position:
        build: "./atomic/position"
        image: "weihaosmu/position:1.0.0"
        environment:
            - dbURL=mysql+mysqlconnector://is213@host.docker.internal:3306/position
        ports:
            - "5011:5011"

    rabbitmq:
        image: "rabbitmq:3-management"
        hostname: "rabbitmq"
        ports:
            - "5672:5672"
            - "15672:15672"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:15672"]
            interval: 30s
            timeout: 10s
            retries: 5

    monitoring:
        build: "./atomic/monitoring"
        image: "weihaosmu/monitoring:1.0.0"
        environment:
            - dbURL=mysql+mysqlconnector://is213@host.docker.internal:3306/monitoring
        restart: on-failure
        depends_on:
            - rabbitmq
        links:
            - rabbitmq

    notification:
        build: "./atomic/notification"
        image: "weihaosmu/notification:1.0.0"
        restart: on-failure
        depends_on:
            - rabbitmq
        links:
            - rabbitmq

    login:
        build: "./composite/login"
        image: "weihaosmu/login:1.0.0"
        ports:
            - "5013:5013"
        depends_on:
            - account

    createposition:
        build: "./composite/createposition"
        image: "weihaosmu/createposition:1.0.0"
        ports:
            - "5012:5012"
        depends_on:
            - account

    checkbalance:
        build: "./composite/checkbalance"
        image: "weihaosmu/checkbalance:1.0.0"
        ports:
            - "5101:5101"
        depends_on:
            - account

    changeequip:
        build: "./composite/changeequip"
        image: "weihaosmu/changeequip:1.0.0"
        ports:
            - "5102:5102"
        depends_on:
            - account
            - accessory

    populateaccessories:
        build: "./composite/populateaccessories"
        image: "weihaosmu/populateaccessories:1.0.0"
        ports:
            - "5100:5100"
        depends_on:
            - shop
            - inventory
            - accessory

    purchaseaccessories:
        build: "./composite/purchaseaccessories"
        image: "weihaosmu/purchaseaccessories:1.0.0"
        ports:
            - "5200:5200"
        depends_on:
            - shop
            - inventory
            - accessory